### ISSUE TITLE
Is this always true on 0.17 ?

### ISSUE THREAD

**Issue by Swizz** [mbylstra/call-elm-functions-from-js-dont-do-this#1]
Hi,

I am trying to develop an image processing proof of concept about nudity detection.
I have chosen Elm due to its clean structure but Elm seems to be built for UI stuff.

So, I need a clean way to access to my Elm functions through a simple entry point ; and ports seem to be a little tricky.
Because my final objective is to give my code as a common JS library.

Your proposal seem to be the best way to realise my wish with just some encapsulation work.

Regards,

**Comment by mbylstra** [comment]
Hi,

The code in this repo will only work for 0.16. The internals have changed considerably for 0.17. I'm not sure the same thing is possible, but being JS, probably anything is possible. Also, I agree that Elm is a good way to write modules for Javascript, but this hasn't been a goal for Elm so far - there is no officially recommended way to do this, and no stable APIs. 

I believe it might be possible to build a clean API for a JS library using Ports, if the API returned a promise or accepted a callback rather than being a blocking function. If this is possible, I think this might be a better approach.

Good luck!

**Comment by Swizz** [comment]
Thanks for your answer, I will have a look for another way.

Elm have great concepts for data manipulation such as image matrix.
And I did not find any equivalent right now with same simplicity, syntax and concept.
